weight = float(input("Введите ваш вес (кг): "))
height = float(input("Введите ваш рост (м): "))
bmi = weight / (height ** 2)
print("---Отчет о состоянии здоровья пациента---")
print(f"Рост:\t{height}\nВес:\t{weight}")
print(f"Индекс массы тела пациента: {bmi:.2f}")