print("=== Анализ последовательности ДНК ===")
print()
dna = input("Введите последовательность ДНК: ").upper()
print()
print(f"Последовательность в верхнем регистре: {dna}")
print()
print("Подсчёт нуклеотидов:")
count_A = dna.count("A")
count_T = dna.count("T")
count_G = dna.count("G")
count_C = dna.count("C")
print(f"A: {count_A}")
print(f"T: {count_T}")
print(f"G: {count_G}")
print(f"C: {count_C}")
length = len(dna)
print(f"Общая длина: {length} нуклеотидов")